"""Re-download the self-hosted Poppins and Font Awesome assets.

The site must render behind corporate proxies that block third-party origins, so
these files are committed rather than fetched at runtime. This script exists so the
next person can regenerate them instead of guessing which weights and formats to grab.
`tools/check_no_cdn.py` is what stops a CDN reference coming back.

Poppins: latin subset only - the site is English - at the five weights it uses.
400 is the implicit body default and is not written anywhere as `font-weight: 400`.

Font Awesome 5.15.4: woff2 only. The upstream CSS also offers eot/ttf/svg/woff for
browsers that predate 2016; shipping those would quadruple the icon payload for
nobody. The @font-face src blocks are rewritten to point at woff2 alone.

Usage:
    py tools/vendor_assets.py
"""

import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Google serves woff2 only to a browser UA; a plain urllib request gets ttf.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0 Safari/537.36")

POPPINS_CSS = ("https://fonts.googleapis.com/css2"
               "?family=Poppins:wght@400;500;600;700;800&display=swap")
WEIGHT_NAMES = {400: "Regular", 500: "Medium", 600: "SemiBold",
                700: "Bold", 800: "ExtraBold"}

FA_VERSION = "5.15.4"
FA_BASE = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/%s" % FA_VERSION
FA_FONTS = ["fa-brands-400", "fa-regular-400", "fa-solid-900"]


def get(url, ua=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA} if ua else {})
    return urllib.request.urlopen(req).read()


def vendor_poppins():
    out_dir = os.path.join(ROOT, "fonts", "poppins")
    os.makedirs(out_dir, exist_ok=True)
    css = get(POPPINS_CSS, ua=True).decode("utf-8")
    blocks = re.findall(r'/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{.*?\})', css, re.S)
    faces = ["/* Poppins, self-hosted. Latin subset only.",
             "   Generated by tools/vendor_assets.py - do not hand-edit. */"]
    for subset, block in blocks:
        if subset != "latin":
            continue
        weight = int(re.search(r'font-weight:\s*(\d+)', block).group(1))
        url = re.search(r'url\((https://[^)]+)\)', block).group(1)
        unicode_range = re.search(r'unicode-range:\s*([^;]+);', block).group(1)
        name = "Poppins-%s.woff2" % WEIGHT_NAMES[weight]
        with open(os.path.join(out_dir, name), "wb") as fh:
            fh.write(get(url, ua=True))
        faces.append("""@font-face {
  font-family: 'Poppins';
  font-style: normal;
  font-weight: %d;
  font-display: swap;
  src: url('../fonts/poppins/%s') format('woff2');
  unicode-range: %s;
}""" % (weight, name, unicode_range))
        print("poppins %d -> %s" % (weight, name))
    with open(os.path.join(ROOT, "styles", "fonts.css"), "w",
              encoding="utf-8", newline="") as fh:
        fh.write("\n".join(faces) + "\n")


def vendor_fontawesome():
    css_dir = os.path.join(ROOT, "styles", "vendor", "fontawesome", "css")
    font_dir = os.path.join(ROOT, "styles", "vendor", "fontawesome", "webfonts")
    os.makedirs(css_dir, exist_ok=True)
    os.makedirs(font_dir, exist_ok=True)

    for name in FA_FONTS:
        with open(os.path.join(font_dir, "%s.woff2" % name), "wb") as fh:
            fh.write(get("%s/webfonts/%s.woff2" % (FA_BASE, name)))
        print("fontawesome -> %s.woff2" % name)

    css = get("%s/css/all.min.css" % FA_BASE).decode("utf-8")
    css, n = re.subn(
        r'src:url\(\.\./webfonts/([a-z0-9-]+)\.eot\);src:[^}]*?(?=\})',
        lambda m: 'src:url(../webfonts/%s.woff2) format("woff2")' % m.group(1), css)
    if n != len(FA_FONTS):
        print("expected %d @font-face blocks, rewrote %d - upstream CSS changed shape"
              % (len(FA_FONTS), n))
        return 1
    with open(os.path.join(css_dir, "all.min.css"), "w",
              encoding="utf-8", newline="") as fh:
        fh.write(css)
    return 0


def main():
    vendor_poppins()
    return vendor_fontawesome()


if __name__ == "__main__":
    sys.exit(main())
